services:
  - type: web
    name: django-backend
    env: python
    root: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    autoDeploy: true
